services:
  modbus-interview:
    image: modbussimulator:latest
    pull_policy: never
    container_name: modbus-simulator
    command: ["python", "-u", "server.py"]
    restart: unless-stopped
    ports:
      - "8052:502"
    environment:
      PYTHONPATH: /shared
    volumes:
      - ./instances/Interview:/app
      - ./equipment.py:/shared/equipment.py:ro
    networks:
      - ignition_ignition-net

  modbus-trainer:
    image: modbussimulator:latest
    pull_policy: never
    container_name: modbus-simulator-2
    command: ["python", "-u", "server.py"]
    restart: unless-stopped
    ports:
      - "8053:502"
    environment:
      PYTHONPATH: /shared
    volumes:
      - ./instances/Trainer:/app
      - ./equipment.py:/shared/equipment.py:ro
    networks:
      - ignition_ignition-net

networks:
  ignition_ignition-net:
      external: true